name: MongoDB Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MongoDB Tools
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-database-tools

    - name: Create Backup
      run: |
        mongodump --uri="${{ secrets.MONGODB_URI }}" --archive=backup.gz --gzip

    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy backup to S3
      run: |
        aws s3 cp backup.gz s3://${{ secrets.AWS_S3_BUCKET }}/mongodb-backups/backup-$(date +%Y-%m-%d).gz
